In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import gym

In [2]:
env = gym.make('CartPole-v0')

In [3]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps",format(t+1))
            break

[-0.00021277 -0.01202032  0.04565653 -0.04344655]
[-0.00045318 -0.20776622  0.0447876   0.26328468]
[-0.0046085  -0.01331122  0.05005329 -0.01494216]
[-0.00487473  0.1810585   0.04975445 -0.29142207]
[-0.00125356 -0.01473627  0.04392601  0.01652841]
[-0.00154828  0.1797291   0.04425658 -0.26197818]
[ 0.0020463   0.37419229  0.03901701 -0.54038016]
[ 0.00953015  0.5687447   0.02820941 -0.82051858]
[ 0.02090504  0.76346949  0.01179904 -1.10419709]
[ 0.03617443  0.95843429 -0.0102849  -1.3931551 ]
[ 0.05534312  1.15368275 -0.038148   -1.689036  ]
[ 0.07841677  1.3492243  -0.07192872 -1.99334773]
[ 0.10540126  1.1549252  -0.11179568 -1.7237815 ]
[ 0.12849976  0.9612462  -0.14627131 -1.46787612]
[ 0.14772469  1.15782417 -0.17562883 -1.80244488]
Episode finished after {} timesteps 15
[-0.0045843   0.0220235   0.01571586 -0.00398944]
[-0.00414383 -0.17332028  0.01563607  0.2936103 ]
[-0.00761024 -0.36866163  0.02150827  0.59118333]
[-0.01498347 -0.56407799  0.03333194  0.89056303]
[-0.0262650

In [4]:
env.close()